local M = {}

local function lines()
  return {
    "NEOVIM CHEAT SHEET - Complete Guide",
    "================================================================",
    "",
    "📁 PROJECT / GENERAL",
    "  <Space>w            Save file (manual - auto-save is enabled)",
    "  <Space>q            Quit window",
    "  <Space>e            Toggle file tree",
    "  <Space>ff           Find files (Telescope)",
    "  <Space>fg           Live grep (search in files)",
    "  <Space>fb           List open buffers",
    "  <Space>?            Open this cheat sheet",
    "  <Space>z            Focus mode (Zen Mode toggle)",
    "  <Space>ta           Toggle auto-save on/off",
    "",
    "📋 CODE FOLDING (Collapse/Expand)",
    "  <Space>↑            Collapse all (like VSCode)",
    "  <Space>↓            Expand all (like VSCode)",
    "  <Space><Space>      Toggle fold under cursor",
    "  <Space>fc           Close fold under cursor",
    "  <Space>fo           Open fold under cursor",
    "  <Space>ft           Toggle fold under cursor",
    "  zc / zo / za        Close / Open / Toggle fold (native)",
    "",
    "🌳 FILE EXPLORER (NvimTree)",
    "  x                   Cut (move) file/folder",
    "  p                   Paste (after cut)",
    "  r                   Rename",
    "  d                   Delete",
    "  a                   Create file/dir (add trailing / for dir)",
    "  R                   Refresh tree",
    "  q                   Close tree",
    "",
    "💻 TERMINAL / RUN",
    "  <Space>t            Open terminal (bottom split)",
    "  <Space>rp           Run current Python file (.venv)",
    "  :q                  Close terminal (in terminal window)",
    "  Ctrl+\\ Ctrl+n      Exit terminal mode to normal mode",
    "",
    "🤖 AI / LLM (AVANTE - Claude Sonnet 4.5)",
    "  <Space>aa           Ask AI (in normal mode: about file, in visual: selection)",
    "  <Space>ac           Open persistent AI chat",
    "  <Space>at           Toggle AI sidebar",
    "  <Space>af           Focus AI sidebar",
    "  <Space>ar           Refresh AI sidebar",
    "  <Space>aB           Add all buffers to AI context",
    "  <Space>as           Show repo map",
    "  <Space>aS           Clear/Stop AI request",
    "",
    "  Inside Avante Sidebar:",
    "  ]p / [p             Next / previous prompt",
    "  a                   Apply at cursor",
    "  A                   Apply all suggestions",
    "  r                   Retry request",
    "  e                   Edit request",
    "  @                   Add file to context",
    "  d                   Remove file from context",
    "  q                   Close sidebar",
    "  Tab / Shift+Tab     Switch between windows",
    "",
    "✨ CODE COMPLETION (in Insert mode)",
    "  Ctrl+Space          Trigger completion menu",
    "  Tab                 Accept current completion",
    "  Shift+Tab           Previous completion item",
    "  Ctrl+e              Close completion menu",
    "  Enter               Accept completion",
    "  [AI]                Copilot AI suggestion",
    "  [LSP]               Language server suggestion",
    "  [Buf]               Buffer word suggestion",
    "  [Path]              File path suggestion",
    "",
    "🐛 DEBUGGER (PYTHON / DEBUGPY)",
    "  <Space>dc           Start / Continue debug",
    "  <Space>dn           Step over (next line)",
    "  <Space>di           Step into (enter function)",
    "  <Space>do           Step out (exit function)",
    "  <Space>db           Toggle breakpoint",
    "  <Space>dB           Conditional breakpoint",
    "  <Space>dr           Open debug REPL",
    "  <Space>du           Toggle debug UI",
    "  <Space>dl           Run last debug session",
    "  <Space>dq           Stop debugging / terminate",
    "  <Space>df           FastAPI AWS debug helper",
    "",
    "  FastAPI debug workflow:",
    "    Terminal: python -Xfrozen_modules=off -m debugpy --listen 5678",
    "              --wait-for-client -m uvicorn app:fast_app --port 8000",
    "    Neovim: <Space>dc → Choose: Attach (debugpy :5678)",
    "",
    "📄 LSP (Language Server - Code Intelligence)",
    "  gd                  Go to definition",
    "  gD                  Go to declaration",
    "  gi                  Go to implementation",
    "  gt                  Go to type definition",
    "  gr                  Find references (Telescope)",
    "  K                   Hover documentation",
    "  <Space>rn           Rename symbol",
    "  <Space>ca           Code actions (fixes/refactors)",
    "  <Space>f            Format document",
    "  ]d / [d             Next / previous diagnostic",
    "  <Space>e            Show diagnostic popup",
    "",
    "  LSP Management:",
    "  :Mason              Open Mason (LSP installer)",
    "  :LspInfo            Show LSP status",
    "  :LspRestart         Restart LSP servers",
    "  :LspPythonPath      Show Python path (for .venv)",
    "",
    "🔍 PREVIEWS",
    "  <Space>mp           Markdown: Preview toggle",
    "  <Space>ms           Markdown: Preview stop",
    "  <Space>cv           CSV: Table view toggle",
    "",
    "🔀 GIT / VERSION CONTROL",
    "  <Space>gs           Git status (Neogit)",
    "  <Space>gm           Git menu (GitLens-style popup)",
    "",
    "  Git Hunks:",
    "  ]c / [c             Next / previous git hunk",
    "  <Space>gh           Preview hunk",
    "  <Space>gr           Reset hunk",
    "",
    "  Git Blame:",
    "  <Space>gb           Toggle inline blame (shows author on line)",
    "  <Space>gk           Toggle hover blame popup (on cursor hold)",
    "  <Space>gB           Full blame info (commit details popup)",
    "",
    "  Git Diff/History:",
    "  <Space>go           Open diff view (see all changes)",
    "  <Space>gq           Close diff view",
    "  <Space>gf           Current file commit history",
    "  <Space>gF           Full repo commit history",
    "  <Space>gd           Diff current file against HEAD",
    "",
    "  Inside Neogit:",
    "  s                   Stage hunk/file",
    "  u                   Unstage hunk/file",
    "  c                   Commit",
    "  p                   Push",
    "  P                   Pull",
    "  q                   Close Neogit",
    "",
    "🪟 WINDOWS / SPLITS",
    "  <C-w>w              Cycle through splits",
    "  <C-w>=              Equalize split sizes",
    "  <C-h>               Move to left split",
    "  <C-j>               Move to bottom split",
    "  <C-k>               Move to top split",
    "  <C-l>               Move to right split",
    "  :split              Horizontal split",
    "  :vsplit             Vertical split",
    "  :q                  Close current split",
    "",
    "🎯 VIM MODES (Essential for Beginners!)",
    "  i                   Insert mode (before cursor)",
    "  a                   Insert mode (after cursor)",
    "  I                   Insert at start of line",
    "  A                   Insert at end of line",
    "  Esc                 Return to Normal mode",
    "  v                   Visual mode (select characters)",
    "  V                   Visual line mode (select lines)",
    "  Ctrl+v              Visual block mode (select columns)",
    "",
    "🚀 NAVIGATION MOTIONS (Normal mode)",
    "  Basic movement:",
    "  h j k l             Left / down / up / right",
    "",
    "  Word movement:",
    "  w                   Next word start",
    "  W                   Next WORD start (ignores punctuation)",
    "  b                   Previous word start",
    "  B                   Previous WORD start",
    "  e                   Next word end",
    "  E                   Next WORD end",
    "",
    "  Line movement:",
    "  0                   Start of line",
    "  ^                   First non-blank character",
    "  $                   End of line",
    "  g_                  Last non-blank character",
    "",
    "  File navigation:",
    "  gg                  Go to top of file",
    "  G                   Go to bottom of file",
    "  <number>G           Go to line number (e.g., 42G)",
    "  <number>gg          Go to line number (e.g., 42gg)",
    "  %                   Jump to matching bracket/paren",
    "",
    "  Paragraph/Block:",
    "  {                   Previous paragraph/block",
    "  }                   Next paragraph/block",
    "",
    "  Screen navigation:",
    "  H                   Top of screen (High)",
    "  M                   Middle of screen",
    "  L                   Bottom of screen (Low)",
    "  Ctrl+u              Scroll up half page",
    "  Ctrl+d              Scroll down half page",
    "  Ctrl+b              Scroll up full page (Back)",
    "  Ctrl+f              Scroll down full page (Forward)",
    "  zz                  Center cursor on screen",
    "",
    "🔍 SEARCH & FIND",
    "  /text               Search forward",
    "  ?text               Search backward",
    "  n                   Next match",
    "  N                   Previous match",
    "  *                   Search word under cursor (forward)",
    "  #                   Search word under cursor (backward)",
    "  :noh                Clear search highlighting",
    "",
    "✏️  EDITING BASICS",
    "  Moving lines (VSCode-style):",
    "  <Space>k / <Space>j Move line/selection up/down",
    "",
    "  Deleting:",
    "  x                   Delete character under cursor",
    "  X                   Delete character before cursor",
    "  dd                  Delete line",
    "  dw                  Delete word",
    "  D                   Delete to end of line",
    "  d$                  Delete to end of line (same as D)",
    "  d0                  Delete to start of line",
    "",
    "  Copying (yanking):",
    "  yy                  Yank (copy) line",
    "  yw                  Yank word",
    "  y$                  Yank to end of line",
    "  y0                  Yank to start of line",
    "",
    "  Pasting:",
    "  p                   Paste after cursor/line",
    "  P                   Paste before cursor/line",
    "",
    "  Changing (delete + insert):",
    "  cc                  Change entire line",
    "  cw                  Change word",
    "  C                   Change to end of line",
    "  ciw                 Change inner word (cursor anywhere in word)",
    "  caw                 Change around word (includes spaces)",
    "  ci\"                 Change inside quotes",
    "  ci(                 Change inside parentheses",
    "  ci{                 Change inside braces",
    "",
    "  Replacing:",
    "  r<char>             Replace character under cursor",
    "  R                   Replace mode (overwrite)",
    "",
    "  Indenting:",
    "  >>                  Indent line right",
    "  <<                  Indent line left",
    "  ==                  Auto-indent line",
    "",
    "  New lines:",
    "  o                   Open new line below",
    "  O                   Open new line above",
    "",
    "  Undo/Redo:",
    "  u                   Undo",
    "  Ctrl+r              Redo",
    "",
    "🎯 TEXT OBJECTS (use with d/c/y/v)",
    "  iw / aw             Inner word / around word",
    "  is / as             Inner sentence / around sentence",
    "  ip / ap             Inner paragraph / around paragraph",
    "  i\" / a\"             Inside quotes / around quotes",
    "  i' / a'             Inside single quotes / around",
    "  i( / a(             Inside parens / around parens",
    "  i[ / a[             Inside brackets / around brackets",
    "  i{ / a{             Inside braces / around braces",
    "  it / at             Inside HTML tag / around tag",
    "",
    "  Examples:",
    "    diw               Delete inner word",
    "    ci\"               Change text inside quotes",
    "    yap               Yank entire paragraph",
    "    va{               Visual select around braces",
    "",
    "💡 COMMON WORKFLOWS",
    "  Copy line:",
    "    yy → p            Yank line, paste below",
    "",
    "  Move line:",
    "    dd → p            Delete line, paste below",
    "",
    "  Copy word:",
    "    yiw → p           Yank inner word, paste",
    "",
    "  Replace word:",
    "    ciw → type → Esc  Change inner word, type new, exit",
    "",
    "  Select & copy:",
    "    v → move → y      Visual select, yank",
    "",
    "  Duplicate line:",
    "    yy → p            Yank line, paste",
    "",
    "  Delete until character:",
    "    dt<char>          Delete till character (not including)",
    "    df<char>          Delete find character (including)",
    "",
    "📝 COMMAND MODE",
    "  :w                  Save",
    "  :q                  Quit",
    "  :wq or :x           Save and quit",
    "  :q!                 Quit without saving",
    "  :%s/old/new/g       Replace all in file",
    "  :%s/old/new/gc      Replace all (with confirmation)",
    "",
    "================================================================",
    "Close this cheat sheet: press 'q' or Esc",
  }
end

function M.open()
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines())
  vim.bo[buf].buftype = "nofile"
  vim.bo[buf].bufhidden = "wipe"
  vim.bo[buf].swapfile = false
  vim.bo[buf].modifiable = false
  vim.bo[buf].filetype = "markdown"

  local width = math.floor(vim.o.columns * 0.8)
  local height = math.floor(vim.o.lines * 0.8)
  local row = math.floor((vim.o.lines - height) / 2)
  local col = math.floor((vim.o.columns - width) / 2)

  local win = vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width = width,
    height = height,
    row = row,
    col = col,
    style = "minimal",
    border = "rounded",
  })

  vim.wo[win].wrap = false
  vim.wo[win].number = false
  vim.wo[win].relativenumber = false

  -- Close with q or Esc
  vim.keymap.set("n", "q", "<cmd>close<CR>", { buffer = buf, silent = true })
  vim.keymap.set("n", "<Esc>", "<cmd>close<CR>", { buffer = buf, silent = true })
end

return M
